[package]
name = "isochrone-h3"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dary_heap = "0.3"
h3o = "0.8"
rustc-hash = "2.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
valhalla = { path = "../..", features = ["proto"] }

[dev-dependencies]
pretty_assertions = "1"
