# An isolated environment for tests and sanity checks on CI

FROM rust:slim-bookworm AS builder

# Rust tools
RUN rustup component add rustfmt clippy

# System dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
  # Required for tokio and reqwest via `openssl-sys`
  libssl-dev \
  pkg-config \
  # For some reason GCC fails to compile valhalla so we use clang instead
  clang \
  # Valhalla build dependencies
  build-essential \
  cmake \
  libboost-dev \
  liblz4-dev \
  libprotobuf-dev \
  protobuf-compiler \
  zlib1g-dev

ENV CC=clang
ENV CXX=clang++

WORKDIR /usr/src/app

# First build a dummy target to cache dependencies in a separate Docker layer
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo 'fn main() { println!("Dummy image called!"); }' > src/main.rs
# And for every other target in the workspace
RUN mkdir -p libvalhalla/src && echo '' > libvalhalla/src/lib.rs
COPY libvalhalla/Cargo.toml ./libvalhalla/
RUN cargo build

# Now build the real target
COPY src ./src
COPY libvalhalla ./libvalhalla
# Update modified attribute as otherwise cargo won't rebuild it
RUN touch -a -m ./src/main.rs
RUN touch -a -m ./libvalhalla/src/lib.rs
RUN cargo build

# Check formatting before building to avoid unnecessary rebuilds
RUN cargo fmt --all -- --check

RUN cargo clippy -- -Dwarnings

RUN cargo test
